//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.12 at 07:30:37 PM EDT 
//


package ca.wimsc.server.xml.route;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="route">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="stop" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                           &lt;/sequence>
 *                           &lt;attribute name="dirTag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}Double" />
 *                           &lt;attribute name="lon" type="{http://www.w3.org/2001/XMLSchema}Double" />
 *                           &lt;attribute name="stopId" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="direction" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="stop" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="useForUI" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="path" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="tag">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="point" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}Double" />
 *                                     &lt;attribute name="lon" type="{http://www.w3.org/2001/XMLSchema}Double" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="latMax" type="{http://www.w3.org/2001/XMLSchema}Double" />
 *                 &lt;attribute name="latMin" type="{http://www.w3.org/2001/XMLSchema}Double" />
 *                 &lt;attribute name="lonMax" type="{http://www.w3.org/2001/XMLSchema}Double" />
 *                 &lt;attribute name="lonMin" type="{http://www.w3.org/2001/XMLSchema}Double" />
 *                 &lt;attribute name="oppositeColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="copyright" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "route"
})
@XmlRootElement(name = "body")
public class Body implements Serializable {
    @XmlElement(required = true)
    protected Body.Route route;
    @XmlAttribute
    protected String copyright;

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link Body.Route }
     *     
     */
    public Body.Route getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link Body.Route }
     *     
     */
    public void setRoute(Body.Route value) {
        this.route = value;
    }

    /**
     * Gets the value of the copyright property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * Sets the value of the copyright property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyright(String value) {
        this.copyright = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="stop" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                 &lt;/sequence>
     *                 &lt;attribute name="dirTag" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}Double" />
     *                 &lt;attribute name="lon" type="{http://www.w3.org/2001/XMLSchema}Double" />
     *                 &lt;attribute name="stopId" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                 &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="direction" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="stop" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                           &lt;/sequence>
     *                           &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="useForUI" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="path" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="tag">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                           &lt;/sequence>
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="point" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                           &lt;/sequence>
     *                           &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}Double" />
     *                           &lt;attribute name="lon" type="{http://www.w3.org/2001/XMLSchema}Double" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="latMax" type="{http://www.w3.org/2001/XMLSchema}Double" />
     *       &lt;attribute name="latMin" type="{http://www.w3.org/2001/XMLSchema}Double" />
     *       &lt;attribute name="lonMax" type="{http://www.w3.org/2001/XMLSchema}Double" />
     *       &lt;attribute name="lonMin" type="{http://www.w3.org/2001/XMLSchema}Double" />
     *       &lt;attribute name="oppositeColor" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stop",
        "direction",
        "path"
    })
    public static class Route implements Serializable{

        @XmlElement(required = true)
        protected List<Body.Route.Stop> stop;
        @XmlElement(required = true)
        protected List<Body.Route.Direction> direction;
        @XmlElement(required = true)
        protected List<Body.Route.Path> path;
        @XmlAttribute
        protected String color;
        @XmlAttribute
        protected Double latMax;
        @XmlAttribute
        protected Double latMin;
        @XmlAttribute
        protected Double lonMax;
        @XmlAttribute
        protected Double lonMin;
        @XmlAttribute
        protected String oppositeColor;
        @XmlAttribute
        protected String tag;
        @XmlAttribute
        protected String title;

        /**
         * Gets the value of the stop property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stop property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStop().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Body.Route.Stop }
         * 
         * 
         */
        public List<Body.Route.Stop> getStop() {
            if (stop == null) {
                stop = new ArrayList<Body.Route.Stop>();
            }
            return this.stop;
        }

        /**
         * Gets the value of the direction property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the direction property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDirection().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Body.Route.Direction }
         * 
         * 
         */
        public List<Body.Route.Direction> getDirection() {
            if (direction == null) {
                direction = new ArrayList<Body.Route.Direction>();
            }
            return this.direction;
        }

        /**
         * Gets the value of the path property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the path property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPath().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Body.Route.Path }
         * 
         * 
         */
        public List<Body.Route.Path> getPath() {
            if (path == null) {
                path = new ArrayList<Body.Route.Path>();
            }
            return this.path;
        }

        /**
         * Gets the value of the color property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getColor() {
            return color;
        }

        /**
         * Sets the value of the color property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setColor(String value) {
            this.color = value;
        }

        /**
         * Gets the value of the latMax property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getLatMax() {
            return latMax;
        }

        /**
         * Sets the value of the latMax property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setLatMax(Double value) {
            this.latMax = value;
        }

        /**
         * Gets the value of the latMin property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getLatMin() {
            return latMin;
        }

        /**
         * Sets the value of the latMin property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setLatMin(Double value) {
            this.latMin = value;
        }

        /**
         * Gets the value of the lonMax property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getLonMax() {
            return lonMax;
        }

        /**
         * Sets the value of the lonMax property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setLonMax(Double value) {
            this.lonMax = value;
        }

        /**
         * Gets the value of the lonMin property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getLonMin() {
            return lonMin;
        }

        /**
         * Sets the value of the lonMin property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setLonMin(Double value) {
            this.lonMin = value;
        }

        /**
         * Gets the value of the oppositeColor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOppositeColor() {
            return oppositeColor;
        }

        /**
         * Sets the value of the oppositeColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOppositeColor(String value) {
            this.oppositeColor = value;
        }

        /**
         * Gets the value of the tag property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public String getTag() {
            return tag;
        }

        /**
         * Sets the value of the tag property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTag(String value) {
            this.tag = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="stop" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                 &lt;/sequence>
         *                 &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="useForUI" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "stop"
        })
        public static class Direction implements Serializable{

            @XmlElement(required = true)
            protected List<Body.Route.Direction.Stop> stop;
            @XmlAttribute
            protected String name;
            @XmlAttribute
            protected String tag;
            @XmlAttribute
            protected String title;
            @XmlAttribute
            protected Boolean useForUI;

            /**
             * Gets the value of the stop property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the stop property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getStop().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Body.Route.Direction.Stop }
             * 
             * 
             */
            public List<Body.Route.Direction.Stop> getStop() {
                if (stop == null) {
                    stop = new ArrayList<Body.Route.Direction.Stop>();
                }
                return this.stop;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the tag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTag() {
                return tag;
            }

            /**
             * Sets the value of the tag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTag(String value) {
                this.tag = value;
            }

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the useForUI property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isUseForUI() {
                return useForUI;
            }

            /**
             * Sets the value of the useForUI property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setUseForUI(Boolean value) {
                this.useForUI = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *       &lt;/sequence>
             *       &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Stop implements Serializable{

                @XmlAttribute
                protected String tag;

                /**
                 * Gets the value of the tag property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTag() {
                    return tag;
                }

                /**
                 * Sets the value of the tag property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTag(String value) {
                    this.tag = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="tag">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                 &lt;/sequence>
         *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="point" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                 &lt;/sequence>
         *                 &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}Double" />
         *                 &lt;attribute name="lon" type="{http://www.w3.org/2001/XMLSchema}Double" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tag",
            "point"
        })
        public static class Path implements Serializable{

            @XmlElement(required = true)
            protected Body.Route.Path.Tag tag;
            @XmlElement(required = true)
            protected List<Body.Route.Path.Point> point;

            /**
             * Gets the value of the tag property.
             * 
             * @return
             *     possible object is
             *     {@link Body.Route.Path.Tag }
             *     
             */
            public Body.Route.Path.Tag getTag() {
                return tag;
            }

            /**
             * Sets the value of the tag property.
             * 
             * @param value
             *     allowed object is
             *     {@link Body.Route.Path.Tag }
             *     
             */
            public void setTag(Body.Route.Path.Tag value) {
                this.tag = value;
            }

            /**
             * Gets the value of the point property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the point property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPoint().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Body.Route.Path.Point }
             * 
             * 
             */
            public List<Body.Route.Path.Point> getPoint() {
                if (point == null) {
                    point = new ArrayList<Body.Route.Path.Point>();
                }
                return this.point;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *       &lt;/sequence>
             *       &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}Double" />
             *       &lt;attribute name="lon" type="{http://www.w3.org/2001/XMLSchema}Double" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Point implements Serializable{

                @XmlAttribute
                protected Double lat;
                @XmlAttribute
                protected Double lon;

                /**
                 * Gets the value of the lat property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getLat() {
                    return lat;
                }

                /**
                 * Sets the value of the lat property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setLat(Double value) {
                    this.lat = value;
                }

                /**
                 * Gets the value of the lon property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getLon() {
                    return lon;
                }

                /**
                 * Sets the value of the lon property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setLon(Double value) {
                    this.lon = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *       &lt;/sequence>
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Tag implements Serializable{

                @XmlAttribute
                protected String id;

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setId(String value) {
                    this.id = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *       &lt;/sequence>
         *       &lt;attribute name="dirTag" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}Double" />
         *       &lt;attribute name="lon" type="{http://www.w3.org/2001/XMLSchema}Double" />
         *       &lt;attribute name="stopId" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *       &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Stop implements Serializable{

            @XmlAttribute
            protected String dirTag;
            @XmlAttribute
            protected Double lat;
            @XmlAttribute
            protected Double lon;
            @XmlAttribute
            protected String stopId;
            @XmlAttribute
            protected String tag;
            @XmlAttribute
            protected String title;

            /**
             * Gets the value of the dirTag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Deprecated()
            public String getDirTag() {
                return dirTag;
            }

            /**
             * Sets the value of the dirTag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDirTag(String value) {
                this.dirTag = value;
            }

            /**
             * Gets the value of the lat property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getLat() {
                return lat;
            }

            /**
             * Sets the value of the lat property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setLat(Double value) {
                this.lat = value;
            }

            /**
             * Gets the value of the lon property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getLon() {
                return lon;
            }

            /**
             * Sets the value of the lon property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setLon(Double value) {
                this.lon = value;
            }

            /**
             * Gets the value of the stopId property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public String getStopId() {
                return stopId;
            }

            /**
             * Sets the value of the stopId property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setStopId(String value) {
                this.stopId = value;
            }

            /**
             * Gets the value of the tag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTag() {
                return tag;
            }

            /**
             * Sets the value of the tag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTag(String value) {
                this.tag = value;
            }

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

        }

    }

}
