//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.12 at 07:51:13 PM EDT 
//


package ca.wimsc.server.xml.stops;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="predictions" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="direction">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="prediction" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="block" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="dirTag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="epochTime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                                     &lt;attribute name="isDeparture" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                     &lt;attribute name="minutes" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                     &lt;attribute name="seconds" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                     &lt;attribute name="vehicle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="agencyTitle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="routeTag" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="routeTitle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="stopTag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="stopTitle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="copyright" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "predictions"
})
@XmlRootElement(name = "body")
public class Body implements Serializable{

    @XmlElement(required = true)
    protected List<Body.Predictions> predictions;
    @XmlAttribute
    protected String copyright;

    /**
     * Gets the value of the predictions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the predictions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPredictions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Body.Predictions }
     * 
     * 
     */
    public List<Body.Predictions> getPredictions() {
        if (predictions == null) {
            predictions = new ArrayList<Body.Predictions>();
        }
        return this.predictions;
    }

    /**
     * Gets the value of the copyright property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * Sets the value of the copyright property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyright(String value) {
        this.copyright = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="direction">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="prediction" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                           &lt;/sequence>
     *                           &lt;attribute name="block" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="dirTag" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="epochTime" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                           &lt;attribute name="isDeparture" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                           &lt;attribute name="minutes" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                           &lt;attribute name="seconds" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                           &lt;attribute name="vehicle" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="agencyTitle" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="routeTag" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="routeTitle" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="stopTag" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="stopTitle" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "direction"
    })
    public static class Predictions implements Serializable{

        @XmlElement(required = true)
        protected List<Direction> direction;
        @XmlAttribute
        protected String agencyTitle;
        @XmlAttribute
        protected String routeTag;
        @XmlAttribute
        protected String routeTitle;
        @XmlAttribute
        protected String stopTag;
        @XmlAttribute
        protected String stopTitle;
        @XmlAttribute
        protected String dirTitleBecauseNoPredictions;
        
        public String getDirTitleBecauseNoPredictions() {
            return dirTitleBecauseNoPredictions;
        }

        public void setDirTitleBecauseNoPredictions(String theDirTitleBecauseNoPredictions) {
            dirTitleBecauseNoPredictions = theDirTitleBecauseNoPredictions;
        }

        /**
         * Gets the value of the direction property.
         * 
         * @return
         *     possible object is
         *     {@link Body.Predictions.Direction }
         *     
         */
        public List<Body.Predictions.Direction> getDirection() {
            return direction;
        }

        /**
         * Sets the value of the direction property.
         * 
         * @param value
         *     allowed object is
         *     {@link Body.Predictions.Direction }
         *     
         */
        public void setDirection(List<Direction> value) {
            this.direction = value;
        }

        /**
         * Gets the value of the agencyTitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAgencyTitle() {
            return agencyTitle;
        }

        /**
         * Sets the value of the agencyTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAgencyTitle(String value) {
            this.agencyTitle = value;
        }

        /**
         * Gets the value of the routeTag property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public String getRouteTag() {
            return routeTag;
        }

        /**
         * Sets the value of the routeTag property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setRouteTag(String value) {
            this.routeTag = value;
        }

        /**
         * Gets the value of the routeTitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRouteTitle() {
            return routeTitle;
        }

        /**
         * Sets the value of the routeTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRouteTitle(String value) {
            this.routeTitle = value;
        }

        /**
         * Gets the value of the stopTag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStopTag() {
            return stopTag;
        }

        /**
         * Sets the value of the stopTag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStopTag(String value) {
            this.stopTag = value;
        }

        /**
         * Gets the value of the stopTitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStopTitle() {
            return stopTitle;
        }

        /**
         * Sets the value of the stopTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStopTitle(String value) {
            this.stopTitle = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="prediction" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                 &lt;/sequence>
         *                 &lt;attribute name="block" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="dirTag" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="epochTime" type="{http://www.w3.org/2001/XMLSchema}long" />
         *                 &lt;attribute name="isDeparture" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *                 &lt;attribute name="minutes" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *                 &lt;attribute name="seconds" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *                 &lt;attribute name="vehicle" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "prediction"
        })
        public static class Direction implements Serializable{

            @XmlElement(required = true)
            protected List<Body.Predictions.Direction.Prediction> prediction;
            @XmlAttribute
            protected String title;

            /**
             * Gets the value of the prediction property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the prediction property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPrediction().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Body.Predictions.Direction.Prediction }
             * 
             * 
             */
            public List<Body.Predictions.Direction.Prediction> getPrediction() {
                if (prediction == null) {
                    prediction = new ArrayList<Body.Predictions.Direction.Prediction>();
                }
                return this.prediction;
            }

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *       &lt;/sequence>
             *       &lt;attribute name="block" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="dirTag" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="epochTime" type="{http://www.w3.org/2001/XMLSchema}long" />
             *       &lt;attribute name="isDeparture" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *       &lt;attribute name="minutes" type="{http://www.w3.org/2001/XMLSchema}integer" />
             *       &lt;attribute name="seconds" type="{http://www.w3.org/2001/XMLSchema}integer" />
             *       &lt;attribute name="vehicle" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Prediction implements Serializable{

                @XmlAttribute
                protected String block;
                @XmlAttribute
                protected String dirTag;
                @XmlAttribute
                protected Long epochTime;
                @XmlAttribute
                protected Boolean isDeparture;
                @XmlAttribute
                protected BigInteger minutes;
                @XmlAttribute
                protected BigInteger seconds;
                @XmlAttribute
                protected String vehicle;

                /**
                 * Gets the value of the block property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBlock() {
                    return block;
                }

                /**
                 * Sets the value of the block property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBlock(String value) {
                    this.block = value;
                }

                /**
                 * Gets the value of the dirTag property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDirTag() {
                    return dirTag;
                }

                /**
                 * Sets the value of the dirTag property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDirTag(String value) {
                    this.dirTag = value;
                }

                /**
                 * Gets the value of the epochTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Long }
                 *     
                 */
                public Long getEpochTime() {
                    return epochTime;
                }

                /**
                 * Sets the value of the epochTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Long }
                 *     
                 */
                public void setEpochTime(Long value) {
                    this.epochTime = value;
                }

                /**
                 * Gets the value of the isDeparture property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isIsDeparture() {
                    return isDeparture;
                }

                /**
                 * Sets the value of the isDeparture property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setIsDeparture(Boolean value) {
                    this.isDeparture = value;
                }

                /**
                 * Gets the value of the minutes property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getMinutes() {
                    return minutes;
                }

                /**
                 * Sets the value of the minutes property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setMinutes(BigInteger value) {
                    this.minutes = value;
                }

                /**
                 * Gets the value of the seconds property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getSeconds() {
                    return seconds;
                }

                /**
                 * Sets the value of the seconds property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setSeconds(BigInteger value) {
                    this.seconds = value;
                }

                /**
                 * Gets the value of the vehicle property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVehicle() {
                    return vehicle;
                }

                /**
                 * Sets the value of the vehicle property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVehicle(String value) {
                    this.vehicle = value;
                }

            }

        }

    }

}
